### ISSUE TITLE
Add checklist issue number to config.json

### ISSUE THREAD

**Issue by joeltaylor** [exercism/x-api#109]
Now that we've added a "Help Launch" section to upcoming languages, it'd be really nice to link directly to the checklist issue for the course instead of linking with search params [(source)](https://github.com/exercism/exercism.io/blob/master/x/docs/md/track/LAUNCH.md).

We can add the checklist issue number to the config.json and safely default it to 1 since @kytrinyx posts the issue via the API as soon as a language repo is created.

**Comment by kytrinyx** [comment]
+100 Thanks for remembering to add this issue.

Here's the list of repositories that have an open "Launch Checklist" issue:

- [ ] assembly    [4] https://github.com/exercism/xassembly/issues/4
- [ ] bash        [4] https://github.com/exercism/xbash/issues/4
- [ ] c           [8] https://github.com/exercism/xc/issues/8
- [ ] coldfusion  [1] https://github.com/exercism/xcoldfusion/issues/1
- [ ] crystal     [1] https://github.com/exercism/xcrystal/issues/1
- [ ] dlang       [6] https://github.com/exercism/xdlang/issues/6
- [ ] groovy      [9] https://github.com/exercism/xgroovy/issues/9
- [ ] haxe        [2] https://github.com/exercism/xhaxe/issues/2
- [ ] kotlin      [1] https://github.com/exercism/xkotlin/issues/1
- [ ] nim         [13] https://github.com/exercism/xnim/issues/13
- [ ] perl6       [30] https://github.com/exercism/xperl6/issues/30
- [ ] pony        [1] https://github.com/exercism/xpony/issues/1
- [ ] powershell  [4] https://github.com/exercism/xpowershell/issues/4
- [ ] r           [5] https://github.com/exercism/xr/issues/5
- [ ] racket      [1] https://github.com/exercism/xracket/issues/1
- [ ] sml         [8] https://github.com/exercism/xsml/issues/8
- [ ] tcl         [1] https://github.com/exercism/xtcl/issues/1
- [ ] teco        [1] https://github.com/exercism/xteco/issues/1
- [ ] vbnet       [3] https://github.com/exercism/xvbnet/issues/3

**Comment by joeltaylor** [comment]
Thanks!

I still need to locate where the `config.json` is generated for new tracks and add `checklist_issue` with the default value of `"1"`.

**Comment by kytrinyx** [comment]
Here you go: https://github.com/exercism/x-template

**Comment by joeltaylor** [comment]
I've gone ahead and opened PRs for the above tracks except for those that have a Launch Checklist issue of 1 since we're defaulting to that.

Once this PR and the others are merged, we can move forward with https://github.com/exercism/exercism.io/issues/2875

**Comment by kytrinyx** [comment]
Bam! We are good to go.
